app/urls.py
from core.nomina import views
from django.views.generic import RedirectView
"""
URL configuration for app project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from core.menu.views import login_view

urlpatterns = [
    # Redirección de la URL raíz a '/menu/admin_menu'
    path('', RedirectView.as_view(url='/menu/login/', permanent=True)),
    
    path('admin/', admin.site.urls),
    path('menu/', include("core.menu.urls")),
    path('nomina/', include("core.nomina.urls")),
    path('eventos/', include("core.eventos.urls")),
    path('clientes/', include("core.clientes.urls")),
    path('diario/', include("core.diario.urls")),
    path('dashboard/', include("core.dashboard.urls")),
    path('usuarios/', include("core.usuarios.urls")),
    path('inventario/', include("core.inventario.urls")),
    path('facturacion/', include("core.facturacion.urls")),
    path('sitioweb/', include("core.sitioweb.urls")),
    path('compras/', include("core.compras.urls")),
    path('ventas/', include("core.ventas.urls")),
]

core/usuarios/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'usuarios'

urlpatterns = [
    ###### URLS DE USUARIO ######
    path("", views.IndexView.as_view(), name="index"),
    path('usuarios/crear/', UserCreateView.as_view(), name='registrar_usuario'),
    path("<int:pk>/", views.UserReadView.as_view(), name="consultar_usuario"),
    ###### URLS DE ROL ######
    path("roles/", views.IndexRolView.as_view(), name="index_roles"),
    path('roles/crear/', RolCreateView.as_view(), name='registrar_rol'),
    path("roles/<int:pk>/", views.RolReadView.as_view(), name="consultar_rol"),
    path('roles/<int:pk>/editar/', RolUpdateView.as_view(), name='modificar_rol'),
    path('roles/<int:pk>/eliminar/', RolDeleteView.as_view(), name='eliminar_rol'),
    ###### URLS DE PERMISO ######
    path("permisos/", views.IndexPermisoView.as_view(), name="index_permisos"),
    path('permisos/crear/', PermisoCreateView.as_view(), name='registrar_permiso'),
    path("permisos/<int:pk>/", views.PermisoReadView.as_view(), name="consultar_permiso"),
    path('permisos/<int:pk>/editar/', PermisoUpdateView.as_view(), name='modificar_permiso'),
    path('permisos/<int:pk>/eliminar/', PermisoDeleteView.as_view(), name='eliminar_permiso'),
]

core/usuarios/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from core.nomina.models import Empleado

class Permiso(models.Model):
    permiso_id = models.AutoField(primary_key=True)
    permiso_nombre = models.CharField(max_length=50)
    permiso_tipo = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.permiso_nombre} - {self.permiso_tipo}"

    class Meta:
        managed = False
        db_table = 'permiso'


class Rol(models.Model):
    rol_id = models.AutoField(primary_key=True)
    rol_nombre = models.CharField(max_length=50)
    rol_descripcion = models.CharField(max_length=150)

    class Meta:
        managed = False
        db_table = 'rol'


class RolPermiso(models.Model):
    fk_rol = models.OneToOneField(Rol, models.DO_NOTHING, db_column='fk_rol', primary_key=True)  # The composite primary key (fk_rol, fk_permiso) found, that is not supported. The first column is selected.
    fk_permiso = models.ForeignKey(Permiso, models.DO_NOTHING, db_column='fk_permiso')

    class Meta:
        managed = False
        db_table = 'rol_permiso'
        unique_together = (('fk_rol', 'fk_permiso'),)


class Usuario(models.Model):
    usuario_id = models.AutoField(primary_key=True)
    usuario_nombre = models.CharField(unique=True, max_length=50)
    usuario_contrasena = models.CharField(max_length=50)
    fk_empleado = models.ForeignKey(Empleado, models.DO_NOTHING, db_column='fk_empleado')

    class Meta:
        managed = False
        db_table = 'usuario'


class UsuarioRol(models.Model):
    fk_usuario = models.OneToOneField(Usuario, models.DO_NOTHING, db_column='fk_usuario', primary_key=True)  # The composite primary key (fk_usuario, fk_rol) found, that is not supported. The first column is selected.
    fk_rol = models.ForeignKey(Rol, models.DO_NOTHING, db_column='fk_rol')

    class Meta:
        managed = False
        db_table = 'usuario_rol'
        unique_together = (('fk_usuario', 'fk_rol'),)

core/usuarios/forms.py
from django import forms
from .models import Usuario
from .models import Rol
from .models import Permiso

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['usuario_nombre', 'usuario_contrasena','fk_empleado']

class RolForm(forms.ModelForm):
    class Meta:
        model = Rol
        fields = ['rol_nombre', 'rol_descripcion', 'permisos']

    permisos = forms.ModelMultipleChoiceField(
        queryset=Permiso.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'permisos-select'})
    )

class PermisoForm(forms.ModelForm):
    class Meta:
        model = Permiso
        fields = ['permiso_nombre', 'permiso_tipo']

core/usuarios/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import *
from .forms import *
from django.views import generic

###### MANEJO DE USUARIOS ######
class IndexView(generic.ListView):
    template_name = "usuarios/index.html"
    context_object_name = "lista_usuarios"

    def get_queryset(self):
        queryset = Usuario.objects.all()
        return queryset
    
class UserCreateView(CreateView):
    model = Usuario
    form_class = UsuarioForm
    success_url = reverse_lazy('usuarios:index')
    
    def get_template_names(self):
        return ['usuarios/registrar_usuario.html'] 
    
class UserReadView(generic.DetailView):
    model = Usuario
    template_name = "usuarios/consultar_usuario.html"
    context_object_name = 'usuario'
    
###### MANEJO DE ROLES ######

class IndexRolView(generic.ListView):
    template_name = "usuarios/index_roles.html"
    context_object_name = "roles_con_permisos"

    def get_queryset(self):
        roles = Rol.objects.all()
        roles_con_permisos = []

        for rol in roles:
            permisos = RolPermiso.objects.filter(fk_rol=rol)
            roles_con_permisos.append({'rol': rol, 'permisos': permisos})

        return roles_con_permisos

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class RolCreateView(CreateView):
    model = Rol
    form_class = RolForm
    success_url = reverse_lazy('usuarios:index_roles')

    def get_template_names(self):
        return ['usuarios/registrar_rol.html']
    
    def form_valid(self, form):
        rol = form.save(commit=False)
        rol.save()
        permisos_seleccionados = form.cleaned_data.get('permisos')
        for permiso in permisos_seleccionados:
            RolPermiso.objects.create(fk_rol=rol, fk_permiso=permiso)
        return super().form_valid(form)
    
class RolReadView(generic.DetailView):
    model = Rol
    template_name = "usuarios/consultar_rol.html"
    context_object_name = 'rol'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rol = self.get_object()
        rol_permisos = RolPermiso.objects.filter(fk_rol=rol)
        context['rol_permisos'] = rol_permisos
        return context

class RolUpdateView(UpdateView):
    model = Rol
    form_class = RolForm
    success_url = reverse_lazy('usuarios:index_roles')  
    
    def get_template_names(self):
        return ['usuarios/modificar_rol.html']
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rol = self.get_object()  # Obtener el objeto Rol
        context['rol'] = rol  # Agregar el objeto Rol al contexto
        return context
    
    def form_valid(self, form):
        rol = form.save(commit=False)
        rol.save()
        permisos_seleccionados = form.cleaned_data.get('permisos')

        # Obtiene los permisos existentes asociados a este rol
        permisos_actuales = RolPermiso.objects.filter(fk_rol=rol)

        # Lista los ids de los permisos actuales
        permisos_actuales_ids = [permiso.fk_permiso.pk for permiso in permisos_actuales]

        # Lista los ids de los permisos seleccionados
        permisos_seleccionados_ids = [permiso.pk for permiso in permisos_seleccionados]

        # Elimina los permisos que están en la base de datos pero no están seleccionados
        for permiso_id in permisos_actuales_ids:
            if permiso_id not in permisos_seleccionados_ids:
                RolPermiso.objects.filter(fk_rol=rol, fk_permiso_id=permiso_id).delete()

        # Agrega los nuevos permisos seleccionados
        for permiso in permisos_seleccionados:
            if permiso.pk not in permisos_actuales_ids:
                RolPermiso.objects.create(fk_rol=rol, fk_permiso=permiso)

        return super().form_valid(form)


class RolDeleteView(DeleteView):
    model = Rol
    success_url = reverse_lazy('usuarios:index_roles')
    template_name = 'usuarios/eliminar_rol.html'  

###### MANEJO DE PERMISOS ######

class IndexPermisoView(generic.ListView):
    template_name = "usuarios/index_permisos.html"
    context_object_name = "lista_permisos"

    def get_queryset(self):
        queryset = Permiso.objects.all()
        return queryset

class PermisoCreateView(CreateView):
    model = Permiso
    form_class = PermisoForm
    success_url = reverse_lazy('usuarios:index_permisos')

    def get_template_names(self):
        return ['usuarios/registrar_permiso.html']
    
class PermisoReadView(generic.DetailView):
    model = Permiso
    template_name = "usuarios/consultar_permiso.html"
    context_object_name = 'permiso'

class PermisoUpdateView(UpdateView):
    model = Permiso
    form_class = PermisoForm
    template_name = 'usuarios/modificar_permiso.html'  
    success_url = reverse_lazy('usuarios:index_permisos')  

class PermisoDeleteView(DeleteView):
    model = Permiso
    success_url = reverse_lazy('usuarios:index_permisos')
    template_name = 'usuarios/eliminar_permiso.html'

core/usuarios/templates/usuarios/consultar_permiso.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Información del Permiso</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: Arial, sans-serif;
            background-color: #FFEBCC;
            margin: 0;
            padding: 20px;
        }

        h1 {
            margin-bottom: 20px;
            text-align: center;
        }

        .info-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            width: 600px;
            margin-bottom: 10px;
            padding: 50px;
        }

        .info {
            display: flex;
            flex-direction: column;
            width: 280px;
            margin-bottom: 10px;
        }

        .label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        .value {
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 4px;
            padding: 8px;
            width: 100%; 
        }

        .button-container {
            display: flex;
            flex-direction: row; /* Cambio a dirección horizontal */
            width: 45%; /* O ajusta el ancho según tu preferencia */
            padding: 15px;
            justify-content: space-between; /* Para distribuir los botones */
        }

        .button-agregar {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: #007bff;
        }

        .button-modificar {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: #007bff;
        }

        .button-eliminar {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: #dc3545;
        }

        .button-lista {
            color: #000000;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: transparent;
        }


    </style>
</head>
<body>
    <h1>Información del Permiso</h1>
    <div class="info-container">
        <div class="info">
            <div class="label">ID:</div>
            <div class="value">{{ permiso.permiso_id }}</div>
        </div>
        <div class="info">
            <div class="label">Nombre:</div>
            <div class="value">{{ permiso.permiso_nombre }}</div>
        </div>
        <div class="info">
            <div class="label">Tipo de permiso:</div>
            <div class="value">{{ permiso.permiso_tipo }}</div>
        </div>
    </div>

        <div class="button-container">
            <a href="{% url 'usuarios:modificar_permiso' permiso.permiso_id %}" class="button-modificar">Modificar Permiso</a>
            <a href="#" onclick="mostrarModal()" class="button-eliminar">Eliminar Permiso</a>
            <a href="{% url 'usuarios:index_permisos' %}" class="button-lista">Volver a la lista de Permisos</a>
        </div>
    <!-- Modal -->
    <div id="myModal" class="modal" style="display: none;">
        <div class="modal-content">
            <span class="close" onclick="cerrarModal()">&times;</span>
            {% include 'usuarios/eliminar_permiso.html' %}
        </div>
    </div>

    <script>
        function mostrarModal() {
            document.getElementById('myModal').style.display = 'block';
        }

        function cerrarModal() {
            document.getElementById('myModal').style.display = 'none';
        }
    </script>
</body>
</html>

core/usuarios/templates/usuarios/consultar_rol.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Información del Rol</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: Arial, sans-serif;
            background-color: #FFEBCC;
            margin: 0;
            padding: 20px;
        }

        h1 {
            margin-bottom: 20px;
            text-align: center;
        }

        .info-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            width: 600px;
            margin-bottom: 10px;
            padding: 50px;
        }

        .info {
            display: flex;
            flex-direction: column;
            width: 280px;
            margin-bottom: 10px;
        }

        .label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        .value {
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 4px;
            padding: 8px;
            width: 100%; 
        }

        .button-container {
            display: flex;
            flex-direction: row; /* Cambio a dirección horizontal */
            width: 45%; /* O ajusta el ancho según tu preferencia */
            padding: 15px;
            justify-content: space-between; /* Para distribuir los botones */
        }

        .button-agregar {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: #007bff;
        }

        .button-modificar {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: #007bff;
        }

        .button-eliminar {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: #dc3545;
        }

        .button-lista {
            color: #000000;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: transparent;
        }


    </style>
</head>
<body>
    <h1>Información del Rol</h1>
    <div class="info-container">
        <div class="info">
            <div class="label">ID:</div>
            <div class="value">{{ rol.rol_id }}</div>
        </div>
        <div class="info">
            <div class="label">Nombre:</div>
            <div class="value">{{ rol.rol_nombre }}</div>
        </div>
        <div class="info">
            <div class="label">Descripción:</div>
            <div class="value">{{ rol.rol_descripcion }}</div>
        </div>
        <div class="info">
            <div class="label">Permisos:</div>
            <div class="value">
                {% for rol_permiso in rol_permisos %}
                    {{ rol_permiso.fk_permiso.permiso_nombre }} ({{ rol_permiso.fk_permiso.permiso_tipo }})
                    {% if not forloop.last %}, {% endif %}
                {% empty %}
                    Sin permisos asignados
                {% endfor %}
            </div>
        </div>
    </div>

        <div class="button-container">
            <a href="{% url 'usuarios:modificar_rol' rol.rol_id %}" class="button-modificar">Modificar Rol</a>
            <a href="#" onclick="mostrarModal()" class="button-eliminar">Eliminar Rol</a>
            <a href="{% url 'usuarios:index_roles' %}" class="button-lista">Volver a la lista de Roles</a>
        </div>
    <!-- Modal -->
    <div id="myModal" class="modal" style="display: none;">
        <div class="modal-content">
            <span class="close" onclick="cerrarModal()">&times;</span>
            {% include 'usuarios/eliminar_rol.html' %}
        </div>
    </div>

    <script>
        function mostrarModal() {
            document.getElementById('myModal').style.display = 'block';
        }

        function cerrarModal() {
            document.getElementById('myModal').style.display = 'none';
        }
    </script>
</body>
</html>

core/usuarios/templates/usuarios/eliminar_permiso.html
<!DOCTYPE html>
<html lang="en">
<style>
    .modal {
    display: none;
    position: fixed;
    z-index: 1;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgba(0,0,0,0.4);
    }

    /* Contenido del modal */
    .modal-content {
    background-color: #fefefe;
    margin: 15% auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
    }

    /* Botón para cerrar el modal */
    .close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
    }

    .close:hover,
    .close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
    }

    #eliminarForm {
        margin-top: 20px;
    }

    #eliminarForm input[type="submit"] {
        padding: 15px 25px;
        background-color: #dc3545;
        color: white;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        text-align: center;
        font-size: 16px;
        cursor: pointer;
    }

    #eliminarForm input[type="submit"]:hover {
        background-color: #c82333;
    }
</style>
<body>
    <h2>¿Estás seguro de que deseas eliminar el permiso "{{ permiso.permiso_nombre}}" del tipo "{{ permiso.permiso_tipo}}"?</h2>

    <form id="eliminarForm" method="post" action="{% url 'usuarios:eliminar_permiso' permiso.permiso_id %}">
        {% csrf_token %}
        <input type="submit" value="Eliminar">
    </form>

    <script>
        // Función para mostrar el modal
        function mostrarModal() {
            document.getElementById('myModal').style.display = 'block';
        }

        // Función para cerrar el modal
        function cerrarModal() {
            document.getElementById('myModal').style.display = 'none';
        }

        // Evento al enviar el formulario en el modal
        document.getElementById('modalEliminarForm').addEventListener('submit', function() {
            document.getElementById('modalEliminarForm').action = "{% url 'usuarios:eliminar_permiso' permiso.permiso_id %}";
        });
    </script>
</body>
</html>

core/usuarios/templates/usuarios/eliminar_rol.html
{% comment %} <h2>¿Estás seguro de que deseas eliminar el rol "{{ rol.rol_nombre}}"?</h2>

<form method="post" action="{% url 'usuarios:eliminar_rol' rol.rol_id %}">
    {% csrf_token %}
    <input type="submit" value="Eliminar">
</form> {% endcomment %}

<!DOCTYPE html>
<html lang="en">
<style>
.modal {
  display: none;
  position: fixed;
  z-index: 1;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: auto;
  background-color: rgba(0,0,0,0.4);
}

/* Contenido del modal */
.modal-content {
  background-color: #fefefe;
  margin: 15% auto;
  padding: 20px;
  border: 1px solid #888;
  width: 80%;
}

/* Botón para cerrar el modal */
.close {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}

#eliminarForm {
    margin-top: 20px;
}

#eliminarForm input[type="submit"] {
    padding: 15px 25px;
    background-color: #dc3545;
    color: white;
    border: none;
    border-radius: 4px;
    text-decoration: none;
    text-align: center;
    font-size: 16px;
    cursor: pointer;
}

#eliminarForm input[type="submit"]:hover {
    background-color: #c82333;
}
</style>
<body>
    <h2>¿Estás seguro de que deseas eliminar el rol "{{ rol.rol_nombre}}"?</h2>

    <form id="eliminarForm" method="post" action="{% url 'usuarios:eliminar_rol' rol.rol_id %}">
        {% csrf_token %}
        <input type="submit" value="Eliminar">
    </form>

    <script>
        // Función para mostrar el modal
        function mostrarModal() {
            document.getElementById('myModal').style.display = 'block';
        }

        // Función para cerrar el modal
        function cerrarModal() {
            document.getElementById('myModal').style.display = 'none';
        }

        // Evento al enviar el formulario en el modal
        document.getElementById('modalEliminarForm').addEventListener('submit', function() {
            document.getElementById('modalEliminarForm').action = "{% url 'usuarios:eliminar_rol' rol.rol_id %}";
        });
    </script>
</body>
</html>

core/usuarios/templates/usuarios/index.html
{% extends 'home.html' %}

{% block body %}
    <body class="hold-transition layout-top-nav">
        <div class="wrapper">
            {% include 'header.html' %}

            <div class="content-wrapper">
                <div class="content-header">
                    <div class="container">
                        <div class="row mb-2">
                            <div class="col-sm-6">
                                <h1 class="m-0">
                                    <i class="bi bi-people-fill mr-2" style="color: #685747;"></i> Lista de Usuarios
                                </h1>
                            </div><!-- /.col -->
                            <div class="col-sm-6">
                                <ol class="breadcrumb float-sm-right">
                                    <li class="breadcrumb-item"><a href="{% url 'usuarios:registrar_usuario' %}">Nuevo Usuario</a></li>
                                    <li class="breadcrumb-item"><a href="{% url 'usuarios:index_roles' %}">Roles</a></li>
                                    <li class="breadcrumb-item"><a href="{% url 'usuarios:index_permisos' %}">Permisos</a></li>
                                </ol>
                            </div><!-- /.col -->
                        </div><!-- /.row -->
                    </div><!-- /.container-fluid -->
                </div>
                <div class="content">
                    <div class="container">
                        {% block content %}
                        <style>
                            .espaciado {
                                margin-bottom: 20px; /* Espaciado en la parte inferior */
                                padding-left: 10px;  /* Espaciado en el lado izquierdo */
                                margin-left: auto;
                                margin-right: auto;
                            }
                        
                            body {
                              font-family: Arial, sans-serif;
                          }
                        
                          h2 {
                              margin-bottom: 20px;
                          }
                        
                          table {
                              border-collapse: collapse;
                              width: 80%;
                              margin-left: auto;
                              margin-right: auto; 
                          }
                        
                          th, td {
                              padding: 12px;
                              text-align: left;
                              border-bottom: 1px solid #ddd;
                          }
                        
                          tbody tr:hover {
                              background-color: #DDDDDD;
                          }
                        
                          /* Estilos adicionales para mejorar la apariencia */
                          th {
                              background-color: #f2f2f2;
                          }
                          </style>
                            <table border="1" class="espaciado">
                                <thead>
                                    <tr>
                                        <th>Nombre de Usuario</th>
                                        <th>Contraseña</th>
                                        <th>Empleado</th>
                                        <!-- Agrega más encabezados según los campos de tu modelo Usuario -->
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for usuario in lista_usuarios %}
                                        <tr onclick="window.location='/usuarios/{{ usuario.usuario_id }}';" style="cursor: pointer;">
                                            <td>{{ usuario.usuario_nombre }}</td>
                                            <td>
                                                <span id="passwordField_{{ forloop.counter }}">{{ usuario.usuario_contrasena }}</span>
                                            </td>
                                            <td>{{ usuario.fk_empleado }}</td>
                                        </tr>
                                        <script>
                                            const passwordField_{{ forloop.counter }} = document.getElementById('passwordField_{{ forloop.counter }}');
                                            const password_{{ forloop.counter }} = passwordField_{{ forloop.counter }}.innerText;
                                            passwordField_{{ forloop.counter }}.innerText = '*'.repeat(password_{{ forloop.counter }}.length);
                                        </script>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% endblock %}
                    </div>
                </div>
            </div>
            {% include 'footer.html' %}
        </div>
    </body>
{% endblock %}

core/usuarios/templates/usuarios/registrar_permiso.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registrar Permiso</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #FFEBCC;
            margin: 0;
            padding: 20px;
        }

        h1 {
            text-align: center;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 80%;
            margin: 0 auto;
        }

        form input[type="text"],
        form input[type="email"],
        form select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            display: block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        form button[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 50%; /* Ancho automático basado en el contenido */
            font-size: 18px; /* Tamaño de fuente aumentado */
            margin-left: 280px; /* Espacio superior */
        }

        form button[type="submit"]:hover {
            background-color: #45a049;
        }

        a {
            display: block;
            margin-top: 10px;
            text-align: center;
            text-decoration: none;
            color: #333; /* Cambia el color del enlace a un tono más oscuro */
        }

        a:hover {
            color: #000; /* Cambia el color cuando el cursor pasa sobre el enlace */
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>
    <h1>Registrar Permiso</h1>
    <form method="post" action="{% url 'usuarios:registrar_permiso' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>
    <a href="{% url 'usuarios:index_permisos' %}">Volver a la lista de permisos</a>
</body>
</html>