app/urls.py
from core.nomina import views
from django.views.generic import RedirectView
"""
URL configuration for app project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from core.menu.views import login_view

urlpatterns = [
    # Redirección de la URL raíz a '/menu/admin_menu'
    path('', RedirectView.as_view(url='/menu/login/', permanent=True)),
    
    path('admin/', admin.site.urls),
    path('menu/', include("core.menu.urls")),
    path('nomina/', include("core.nomina.urls")),
    path('eventos/', include("core.eventos.urls")),
    path('clientes/', include("core.clientes.urls")),
    path('diario/', include("core.diario.urls")),
    path('dashboard/', include("core.dashboard.urls")),
    path('usuarios/', include("core.usuarios.urls")),
    path('inventario/', include("core.inventario.urls")),
    path('facturacion/', include("core.facturacion.urls")),
    path('sitioweb/', include("core.sitioweb.urls")),
    path('compras/', include("core.compras.urls")),
    path('ventas/', include("core.ventas.urls")),
]

core/eventos/urls.py
from django.urls import path

from . import views

app_name = 'eventos'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("registrar_evento/", views.EventoCreateView.as_view(), name = "registrar_evento"),
    path("<int:pk>/", views.ConsultarView.as_view(), name="consultar"),
    path("<int:pk>/modificar", views.ModificarEventoView.as_view(), name= "modificar"),
    path('<int:pk>/eliminar/', views.EventoDeleteView.as_view(), name='eliminar'),
    path("<int:evento_id>/registrar_entrada/", views.generar_entradas, name = "registrar_entrada"),
    #path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
]

core/eventos/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from core.nomina.models import *
from core.clientes.models import *


class Evento(models.Model):
    evento_id = models.AutoField(primary_key=True)
    evento_nombre = models.CharField(max_length=50)
    evento_fecha_inicio = models.DateField()
    evento_fecha_fin = models.DateField()
    evento_ubicacion = models.CharField(max_length=100)
    fk_lugar = models.ForeignKey(Lugar, models.DO_NOTHING, db_column='fk_lugar')

    def __str__(self):
        return self.evento_nombre

    class Meta:
        managed = False
        db_table = 'evento'

class Venta(models.Model):
    venta_num = models.IntegerField(primary_key=True)
    venta_fecha = models.DateField()
    venta_total = models.DecimalField(max_digits=10, decimal_places=2)
    fk_tienda = models.ForeignKey(Tienda, models.DO_NOTHING, db_column='fk_tienda')
    fk_natural = models.ForeignKey(Cliente_natural, models.DO_NOTHING, db_column='fk_natural', blank=True, null=True)
    fk_juridico = models.ForeignKey(Cliente_juridico, models.DO_NOTHING, db_column='fk_juridico', blank=True, null=True)
    fk_evento = models.ForeignKey(Evento, models.DO_NOTHING, db_column='fk_evento', blank=True, null=True)

    def __str__(self):
        return self.venta_num

    class Meta:
        managed = False
        db_table = 'venta'


class DetalleVenta(models.Model):
    venta_cantidad = models.IntegerField()
    venta_precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    fk_venta = models.OneToOneField(Venta, models.DO_NOTHING, db_column='fk_venta', primary_key=True)

    def __str__(self):
        return self.fk_venta

    class Meta:
        managed = False
        db_table = 'detalle_venta'

class Entrada(models.Model):
    entrada_id = models.AutoField(primary_key=True)
    entrada_fecha = models.DateField()
    entrada_descripcion = models.CharField(max_length=150)
    entrada_precio = models.DecimalField(max_digits=10, decimal_places=2)
    fk_evento = models.ForeignKey(Evento, models.DO_NOTHING, db_column='fk_evento')
    fk_detalle_venta = models.ForeignKey(DetalleVenta, models.DO_NOTHING, db_column='fk_detalle_venta', blank=True, null=True)

    def __str__(self):
        return self.entrada_id

    class Meta:
        managed = False
        db_table = 'entrada'

core/eventos/forms.py
from django import forms
from .models import Evento, Entrada

class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ['evento_nombre', 'evento_fecha_inicio', 'evento_fecha_fin', 'evento_ubicacion', 'fk_lugar']

class EntradaForm(forms.Form):
    cantidad = forms.IntegerField(min_value=1, label='Cantidad de Entradas')
    precio = forms.DecimalField(min_value=0, label='Precio por Entrada')

core/eventos/views.py
from django.shortcuts import *
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from core.eventos.models import *
from .forms import EventoForm, EntradaForm
from django.views.generic.edit import *
from django.contrib import messages
from django.db import connection

class IndexView(generic.ListView):
    template_name = "eventos/index.html"
    context_object_name = "lista_eventos"

    def get_queryset(self):
        """Return the last five published questions."""
        return Evento.objects.all
    
class ConsultarView(generic.DetailView):
    model = Evento
    template_name = "eventos/consultar.html"
    context_object_name = 'evento'

class ModificarEventoView(UpdateView):
    model = Evento
    template_name = 'eventos/modificar.html'
    fields = ['evento_nombre', 'evento_fecha_inicio', 'evento_fecha_fin', 'evento_ubicacion', 'fk_lugar']
    success_url = reverse_lazy('eventos:index')

class EventoDeleteView(DeleteView):
    model = Evento
    template_name = 'eventos/eliminar.html'
    success_url = reverse_lazy('eventos:index')

def index(request):
    lista_eventos = Evento.objects.all
    template = loader.get_template("eventos/index.html")
    context = {
        "lista_eventos": lista_eventos,
    }
    return HttpResponse(template.render(context, request))

def index(request):
    lista_eventos = Evento.objects.all
    context = {"lista_eventos": lista_eventos}
    return render(request, "eventos/index.html", context)


class EventoCreateView(generic.CreateView):
    model = Evento
    form_class = EventoForm
    template_name = 'eventos/registrar_evento.html'
    
    def get_success_url(self):
        return reverse('eventos:index')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        # Puedes agregar acciones adicionales si es necesario
        return response
    
def generar_entradas(request, evento_id):

    evento = get_object_or_404(Evento, pk=evento_id)

    if request.method == 'POST':
        form = EntradaForm(request.POST)
        if form.is_valid():
            cantidad = form.cleaned_data['cantidad']
            precio = form.cleaned_data['precio']

            with connection.cursor() as cursor:
                cursor.execute("CALL generar_entradas(%s, %s, %s)", [cantidad, precio, evento.evento_id])
            return redirect('eventos:index')
    else:
        form = EntradaForm()

    return render(request, 'eventos/entradas.html', {'form': form})

core/eventos/templates/eventos/consultar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalles del Evento</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: Arial, sans-serif;
            background-color: #FFEBCC;
            margin: 0;
            padding: 20px;
        }

        h1 {
            margin-bottom: 20px;
            text-align: center;
        }

        .info-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            width: 600px;
            margin-bottom: 10px;
            padding: 40px;
        }

        .info {
            display: flex;
            flex-direction: column;
            width: 280px;
            margin-bottom: 10px;
        }

        .label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        .value {
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 4px;
            padding: 8px;
        }

        .button-container {
            display: flex;
            flex-direction: row; /* Alineación horizontal */
            width: 50%;
            justify-content: space-between; /* Distribución equitativa */
            margin-top: 20px; /* Espacio entre los botones y el contenido anterior */
        }

        .button-modificar,
        .button-eliminar,
        .button-lista {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
        }

        .button-modificar {
            background-color: #007bff; /* Azul */
        }

        .button-eliminar {
            background-color: #dc3545; /* Rojo */
        }

        .button-lista {
            background-color: transparent;
            color: #000000;
        }
    </style>
</head>
<body>
    <p>Objeto recibido: {{evento}}</p>
    <h1>Detalles del Evento</h1>
    <div class="info-container">
        <div class="info">
            <div class="label">ID:</div>
            <div class="value">{{ evento.evento_id }}</div>
        </div>
        <div class="info">
            <div class="label">Nombre:</div>
            <div class="value">{{ evento.evento_nombre }}</div>
        </div>
        <div class="info">
            <div class="label">Fecha de Inicio:</div>
            <div class="value">{{ evento.evento_fecha_inicio }}</div>
        </div>
        <div class="info">
            <div class="label">Fecha de Fin:</div>
            <div class="value">{{ evento.evento_fecha_fin }}</div>
        </div>
        <div class="info">
            <div class="label">Ubicación:</div>
            <div class="value">{{ evento.evento_ubicacion }}</div>
        </div>
        <div class="info">
            <div class="label">Lugar:</div>
            <div class="value">{{ evento.fk_lugar }}</div>
        </div>
    </div>

    <div class="button-container">
        <a href="{% url 'eventos:registrar_entrada' evento.evento_id %}" class="button-modificar">Generar Entradas</a>
        <a href="{% url 'eventos:modificar' evento.evento_id %}" class="button-modificar">Modificar evento</a>
        <a href="#" onclick="mostrarModal()" class="button-eliminar">Eliminar Evento</a>
        <a href="{% url 'eventos:index' %}" class="button-lista">Volver a la lista de eventos</a>
    </div>
    <!-- Modal -->
    <div id="myModal" class="modal" style="display: none;">
        <div class="modal-content">
            <span class="close" onclick="cerrarModal()">&times;</span>
            {% include 'eventos/eliminar.html' %}
        </div>
    </div>

    <script>
        function mostrarModal() {
            document.getElementById('myModal').style.display = 'block';
        }

        function cerrarModal() {
            document.getElementById('myModal').style.display = 'none';
        }
    </script>
</body>
</html>

core/eventos/templates/eventos/eliminar.html
<!DOCTYPE html>
<html lang="en">
<style>
    .modal {
    display: none;
    position: fixed;
    z-index: 1;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgba(0,0,0,0.4);
    }

    /* Contenido del modal */
    .modal-content {
    background-color: #fefefe;
    margin: 15% auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
    }

    /* Botón para cerrar el modal */
    .close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
    }

    .close:hover,
    .close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
    }

    #eliminarForm {
        margin-top: 20px;
    }

    #eliminarForm input[type="submit"] {
        padding: 15px 25px;
        background-color: #dc3545;
        color: white;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        text-align: center;
        font-size: 16px;
        cursor: pointer;
    }

    #eliminarForm input[type="submit"]:hover {
        background-color: #c82333;
    }
</style>
<body>
    <h2>¿Estás seguro de que deseas eliminar el evento "{{ evento.evento_nombre }}"?</h2>

    <form method="post" action="{% url 'eventos:eliminar' evento.evento_id %}">
        {% csrf_token %}
        <input type="submit" value="Eliminar">
    </form>

    <script>
        // Función para mostrar el modal
        function mostrarModal() {
            document.getElementById('myModal').style.display = 'block';
        }

        // Función para cerrar el modal
        function cerrarModal() {
            document.getElementById('myModal').style.display = 'none';
        }

        // Evento al enviar el formulario en el modal
        document.getElementById('modalEliminarForm').addEventListener('submit', function() {
            document.getElementById('modalEliminarForm').action = "{% url 'eventos:eliminar' evento.evento_id %}";
        });
    </script>
</body>
</html>

core/eventos/templates/eventos/entradas.html
<body>
    <style>
        body {
            background-color: #FFEBCC;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            color: #333;
        }

        h1 {
            background-color: #FFEBCC;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 30px;
            color: #333;
            font-weight: bold;
            padding: 20px;
            text-align: center;
        }

        form {
            background-color: #fff;
            border: 1px solid #ccc;
            padding: 20px;
            margin: 10px;
            text-align: center;
            font-size: 20px;
        }

        input[type=text],
        input[type=password],
        input[type=email],
        select {
            width: 200px;
            padding: 5px;
            border: 1px solid #ccc;
            margin-bottom: 10px;
        }

        button {
            padding: 5px 10px;
            background-color: #3CA92B;
            border: 0 none;
            cursor: pointer;
            -webkit-border-radius: 5px;
            border-radius: 5px;
            text-align: center;
            font-size: 20px;
            padding: 10px;
        }

        button:hover {
            background-color: green;
        }

        p {
            color: #555;
        }

        .errorlist {
            color: #f00;
        }
    </style>
    <h1>Generar Entradas</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
        <p><a href="{% url 'eventos:index' %}">Volver a la lista de eventos</a></p>
    </form>
</body>

core/eventos/templates/eventos/index.html
{% extends 'home.html'%}

{% block body%}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">

    {% include 'header.html'%}

    <div class="content-wrapper">
        
        <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">
                        <i class="bi bi-calendar-event-fill mr-2" style="color: #685747;"></i> Lista de Eventos
                    </h1>
                </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'eventos:registrar_evento' %}">Nuevo Evento</a></li>
                <li class="breadcrumb-item"><a href="#">Departamentos</a></li>
                </ol>
            </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
        </div>
        <div class = "content">
            <div class = "container"> 
                {% block content%}
                <style>
                    .espaciado {
                        margin-bottom: 20px; /* Espaciado en la parte inferior */
                        padding-left: 10px;  /* Espaciado en el lado izquierdo */
                        margin-left: auto;
                        margin-right: auto;
                    }
                
                    body {
                      font-family: Arial, sans-serif;
                  }
                
                  h2 {
                      margin-bottom: 20px;
                  }
                
                  table {
                      border-collapse: collapse;
                      width: 80%;
                      margin-left: auto;
                      margin-right: auto; 
                  }
                
                  th, td {
                      padding: 12px;
                      text-align: left;
                      border-bottom: 1px solid #ddd;
                  }
                
                  tbody tr:hover {
                    background-color: #DDDDDD;
                }
                
                  /* Estilos adicionales para mejorar la apariencia */
                  th {
                      background-color: #f2f2f2;
                  }
                  </style>
                    <table border="1", style = espaciado>
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Fecha Inicio</th>
                                <th>Fecha Fin</th>
                                <th>Ubicacion</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for evento in lista_eventos %}
                                <tr onclick="window.location='/eventos/{{ evento.evento_id }}';" style="cursor: pointer;">
                                    <td>{{ evento.evento_nombre}}</td>
                                    <td>{{ evento.evento_fecha_inicio }}</td>                      
                                    <td>{{ evento.evento_fecha_fin }}</td>
                                    <td>{{ evento.evento_ubicacion }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endblock %}
            </div>
        </div>
    </div>

        {% include 'footer.html'%}
    </div>
    </body>
{% endblock %}

core/eventos/templates/eventos/modificar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Modificar Evento</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #FFEBCC;
            margin: 0;
            padding: 20px;
        }

        h1 {
            text-align: center;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 80%;
            margin: 0 auto;
        }

        form input[type="text"],
        form input[type="email"],
        form select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            display: block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        form button[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 50%;
            font-size: 18px;
            margin-left: 280px;
        }

        form button[type="submit"]:hover {
            background-color: #45a049;
        }

        a {
            display: block;
            margin-top: 10px;
            text-align: center;
            text-decoration: none;
            color: #333;
        }

        a:hover {
            color: #000;
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>
    <p>Objeto recibido: {{evento}}</p>
    <h1>Modificar Evento</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
        <p><a href="{% url 'eventos:index' %}">Volver a la lista de eventos</a></p>
    </form>
</body>
</html>

core/eventos/templates/eventos/registrar_evento.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registrar Evento</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #FFEBCC;
            margin: 0;
            padding: 20px;
        }

        h1 {
            text-align: center;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 80%;
            margin: 0 auto;
        }

        form input[type="text"],
        form input[type="email"],
        form select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            display: block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        form button[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 50%; /* Ancho automático basado en el contenido */
            font-size: 18px; /* Tamaño de fuente aumentado */
            margin-left: 280px; /* Espacio superior */
        }

        form button[type="submit"]:hover {
            background-color: #45a049;
        }

        a {
            display: block;
            margin-top: 10px;
            text-align: center;
            text-decoration: none;
            color: #333; /* Cambia el color del enlace a un tono más oscuro */
        }

        a:hover {
            color: #000; /* Cambia el color cuando el cursor pasa sobre el enlace */
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>
    <h1>Registrar Evento</h1>
    <form method="post" action="{% url 'eventos:registrar_evento' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>
    <a href="{% url 'eventos:index' %}">Volver a la lista de eventos</a>
</body>
</html>