app/urls.py
from core.nomina import views
from django.views.generic import RedirectView
"""
URL configuration for app project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from core.menu.views import login_view

urlpatterns = [
    # Redirección de la URL raíz a '/menu/admin_menu'
    path('', RedirectView.as_view(url='/menu/login/', permanent=True)),
    
    path('admin/', admin.site.urls),
    path('menu/', include("core.menu.urls")),
    path('nomina/', include("core.nomina.urls")),
    path('eventos/', include("core.eventos.urls")),
    path('clientes/', include("core.clientes.urls")),
    path('diario/', include("core.diario.urls")),
    path('dashboard/', include("core.dashboard.urls")),
    path('usuarios/', include("core.usuarios.urls")),
    path('inventario/', include("core.inventario.urls")),
    path('facturacion/', include("core.facturacion.urls")),
    path('sitioweb/', include("core.sitioweb.urls")),
    path('compras/', include("core.compras.urls")),
    path('ventas/', include("core.ventas.urls")),
]

core/eventos/urls.py
from django.urls import path

from . import views

app_name = 'eventos'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("registrar_evento/", views.EventoCreateView.as_view(), name = "registrar_evento"),
    path("<int:pk>/", views.ConsultarView.as_view(), name="consultar"),
    path("<int:pk>/modificar", views.ModificarEventoView.as_view(), name= "modificar"),
    path('<int:pk>/eliminar/', views.EventoDeleteView.as_view(), name='eliminar'),
    path("<int:evento_id>/registrar_entrada/", views.generar_entradas, name = "registrar_entrada"),
    #path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
]

core/inventario/urls.py
from django.urls import path

from . import views

app_name = 'inventario'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.InventarioConsultarView.as_view(), name="consultar_inventario"),
    path("registrar/", views.registrar_inventario, name="registrar_inventario"),
    path("productos/", views.IndexProductoView.as_view(), name="index_producto"),
    path("ofertas/", views.IndexOfertasView.as_view(), name="index_ofertas"),
    path("productos/registrar/", views.BotellaCreateView.as_view(), name="registrar_producto"),
    path("productos/<int:pk>/", views.BotellaConsultarView.as_view(), name="consultar_producto"),
    path("productos/<int:botella_id>/eliminar/", views.eliminar_producto_view, name="eliminar_producto"),
    path("productos/<int:botella_id>/modificar/", views.modificar_producto, name="modificar_producto"),
    path("productos/<int:botella_id>/ficha/", views.ficha_producto, name="ficha_producto"),
    
]

core/sitioweb/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'sitioweb'

urlpatterns = [
    path('', views.index, name='index'),
    path('productos/', views.productos, name='productos'),
    path('evento/<int:evento_id>/', views.info_evento, name='info_evento'),
    path('producto/<int:botella_id>/', views.info_botella, name='info_producto'),
    path('realizar_compra_botella/<int:botella_id>/', views.realizar_compra_botella, name='realizar_compra_botella'),
    path('realizar_compra/<int:evento_id>/', views.realizar_compra, name='realizar_compra'),
    path('eventos/', views.eventos, name='eventos'),
    path('carrito/', views.carrito, name='carrito'),
    path('carrito/eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('carrito/modificar/<int:producto_id>/', views.modificar_cantidad, name='modificar_cantidad'),
    path('carrito/confirmar/', views.seleccionar_tarjeta, name='seleccionar_tarjeta'),
    path('carrito/confirmar/<int:tarjeta_id>/', views.confirmar_pago, name='confirmar_pago'),
    path('carrito/confirmar/<int:tarjeta_id>/pagar_carrito/', views.pagar_carrito, name='pagar_carrito'),
    path('carrito/registrar_tarjeta/', views.TarjetaCreateView.as_view(), name='registrar_tarjeta'),
    path('afiliacion/', views.afiliacion, name='afiliacion'),
    path('afiliacion/confirmar/', views.seleccionar_tarjeta_afiliacion, name='seleccionar_tarjeta_afiliacion'),
    path('afiliacion/registrar_tarjeta/', views.TarjetaAfiliacionCreateView.as_view(), name='registrar_tarjeta_afiliacion'),
]

core/sitioweb/models.py
from django.db import models

# Create your models here.

core/sitioweb/forms.py
from django import forms
from core.facturacion.models import Tarjeta


class TarjetaForm(forms.ModelForm):
    class Meta:
        model = Tarjeta
        fields = ['tarjeta_numero', 'tarjeta_cvv', 'tarjeta_fecha_vencimiento','tarjeta_banco']

core/eventos/views.py
from django.shortcuts import *
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from core.eventos.models import *
from .forms import EventoForm, EntradaForm
from django.views.generic.edit import *
from django.contrib import messages
from django.db import connection

class IndexView(generic.ListView):
    template_name = "eventos/index.html"
    context_object_name = "lista_eventos"

    def get_queryset(self):
        """Return the last five published questions."""
        return Evento.objects.all
    
class ConsultarView(generic.DetailView):
    model = Evento
    template_name = "eventos/consultar.html"
    context_object_name = 'evento'

class ModificarEventoView(UpdateView):
    model = Evento
    template_name = 'eventos/modificar.html'
    fields = ['evento_nombre', 'evento_fecha_inicio', 'evento_fecha_fin', 'evento_ubicacion', 'fk_lugar']
    success_url = reverse_lazy('eventos:index')

class EventoDeleteView(DeleteView):
    model = Evento
    template_name = 'eventos/eliminar.html'
    success_url = reverse_lazy('eventos:index')

def index(request):
    lista_eventos = Evento.objects.all
    template = loader.get_template("eventos/index.html")
    context = {
        "lista_eventos": lista_eventos,
    }
    return HttpResponse(template.render(context, request))

def index(request):
    lista_eventos = Evento.objects.all
    context = {"lista_eventos": lista_eventos}
    return render(request, "eventos/index.html", context)


class EventoCreateView(generic.CreateView):
    model = Evento
    form_class = EventoForm
    template_name = 'eventos/registrar_evento.html'
    
    def get_success_url(self):
        return reverse('eventos:index')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        # Puedes agregar acciones adicionales si es necesario
        return response
    
def generar_entradas(request, evento_id):

    evento = get_object_or_404(Evento, pk=evento_id)

    if request.method == 'POST':
        form = EntradaForm(request.POST)
        if form.is_valid():
            cantidad = form.cleaned_data['cantidad']
            precio = form.cleaned_data['precio']

            with connection.cursor() as cursor:
                cursor.execute("CALL generar_entradas(%s, %s, %s)", [cantidad, precio, evento.evento_id])
            return redirect('eventos:index')
    else:
        form = EntradaForm()

    return render(request, 'eventos/entradas.html', {'form': form})

core/sitioweb/views.py
from django.shortcuts import render, redirect
from core.inventario.models import Botella
from core.eventos.models import Evento
from core.clientes.models import Cliente_juridico, Cliente_natural
from core.facturacion.models import Tarjeta
from core.facturacion.models import *
from .forms import *
from django.db import connection
from django.views import generic
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django import template

register = template.Library()

@register.filter
def multiply(value, arg):
    return value * arg


def index(request):
    return render(request, 'sitioweb/index.html')

def productos(request):
    productos = Botella.objects.all()
    return render(request, 'sitioweb/productos.html', {'productos': productos})

def eventos(request):
    eventos = Evento.objects.all()
    return render(request, 'sitioweb/eventos.html', {'eventos': eventos})


def obtener_cantidad_entradas(evento_id):
    with connection.cursor() as cursor:
        cursor.execute("CALL obtener_cantidad_entradas(%s, %s)", [evento_id, 0])
        row = cursor.fetchone()
        cantidad_entradas = row[0] if row else None
    return cantidad_entradas

def obtener_precio_entrada(evento_id):
    with connection.cursor() as cursor:
        cursor.execute("CALL obtener_precio_entrada(%s, %s)", [evento_id, 0])
        row = cursor.fetchone()
        precio_entrada = row[0] if row else None
    return precio_entrada

def info_evento(request, evento_id):
    evento = Evento.objects.get(pk=evento_id)
    cantidad_entradas = obtener_cantidad_entradas(evento_id)
    precio_entrada = obtener_precio_entrada(evento_id)
    return render(request, 'sitioweb/info_evento.html', {'evento': evento, 'cantidad_entradas': cantidad_entradas, 'precio_entrada': precio_entrada})

def realizar_compra(request, evento_id):
    if request.method == 'POST':
        cantidad_entradas = int(request.POST.get('cantidad_comprar'))
        precio_unitario = obtener_precio_entrada(evento_id)
        cliente_rif = 1

        with connection.cursor() as cursor:
            cursor.execute("CALL crear_venta_entrada(%s, %s, %s, %s)", [cliente_rif, evento_id, cantidad_entradas, precio_unitario])
            
        return render(request, 'sitioweb/compra_exitosa.html')  # Renderiza el template del modal    
    
    eventos = Evento.objects.all()
    return render(request, 'sitioweb/eventos.html', {'eventos': eventos})

def obtener_precio_botella(evento_id):
    with connection.cursor() as cursor:
        cursor.execute("CALL obtener_precio_entrada(%s, %s)", [evento_id, 0])
        row = cursor.fetchone()
        precio_entrada = row[0] if row else None
    return precio_entrada

def info_botella(request, botella_id):
    botella = Botella.objects.get(pk=botella_id)
    cantidad_botellas = obtener_cantidad_producto(botella_id)
    return render(request, 'sitioweb/info_producto.html', {'botella': botella, 'cantidad_botellas': cantidad_botellas})

def obtener_cantidad_producto(botella_id):
    with connection.cursor() as cursor:
        cursor.execute("CALL obtener_cantidad_botellas(%s, %s)", [botella_id, 0])
        row = cursor.fetchone()
        cantidad_botellas = row[0] if row else None
        print (cantidad_botellas)
    return cantidad_botellas

def realizar_compra_botella(request, botella_id):
    if request.method == 'POST':
        cantidad_botellas = int(request.POST.get('cantidad_comprar'))
        botella = Botella.objects.get(pk=botella_id)
        precio_unitario = botella.botella_precio

        with connection.cursor() as cursor:
            cursor.execute("CALL agregar_producto_al_carrito(%s, %s, %s)", [1, botella_id, cantidad_botellas])
            
        return render(request, 'sitioweb/agregado_exitoso.html')  # Renderiza el template del modal    
    
    return render(request, 'sitioweb/productos.html', {'producto': botella})

def carrito(request):
    cliente_id = 1  # ID del cliente

    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT d.pedido_cantidad, d.pedido_precio_unitario, b.botella_nombre, b.botella_id
            FROM detalle_pedido d
            INNER JOIN presupuesto p ON d.fk_presupuesto = p.presupuesto_num
            INNER JOIN botella b ON d.fk_botella = b.botella_id 
            WHERE p.fk_natural = %s and p.fk_venta is null
            """,
            [cliente_id]
        )
        productos_carrito = cursor.fetchall()
        
        total_carrito = sum(producto[0] * producto[1] for producto in productos_carrito)
        total_fila = [producto[0] * producto[1] for producto in productos_carrito]
        productos_con_total = zip(productos_carrito, total_fila)

    return render(request, 'sitioweb/carrito.html', {'productos_carrito': productos_carrito, 'total_carrito': total_carrito, 'total_fila': total_fila, 'productos_con_total': productos_con_total})


def eliminar_producto(request, producto_id):
    cliente_id = 1 

    with connection.cursor() as cursor:
        cursor.execute("CALL eliminar_producto_carrito(%s, %s)", [producto_id, cliente_id])

    return redirect('sitioweb:carrito')

def modificar_cantidad(request, producto_id):
    cliente_id = 1
    nueva_cantidad = request.POST.get('nueva_cantidad')

    with connection.cursor() as cursor:
        cursor.execute("CALL modificar_cantidad_carrito(%s, %s, %s)", [producto_id, cliente_id, nueva_cantidad])

    return redirect('sitioweb:carrito')

def seleccionar_tarjeta(request):
    rif_cliente = 1
    # lista_tarjetas = Tarjeta.objects.filter(fk_cliente=rif_cliente)
    cliente = Cliente_natural.objects.get(pk=rif_cliente)

    return render(request, 'sitioweb/seleccionar_tarjeta.html', {'cliente': cliente})

class TarjetaCreateView(generic.CreateView):
    model = Tarjeta
    form_class = TarjetaForm
    template_name = 'sitioweb/registrar_tarjeta.html'
    
    def get_success_url(self):
        # Cambia 'consulta_empleado' por 'consultar_empleado'
        return reverse('sitioweb:seleccionar_tarjeta')
    
    def form_valid(self, form):
        # Obtén el objeto Empleado al que deseas asociar el teléfono
        cliente = get_object_or_404(Cliente_natural, pk=1)
        
        # Guarda el teléfono y asócialo al empleado
        self.object = form.save(commit=False)
        self.object.fk_natural = cliente
        self.object.save()

        return super().form_valid(form)
    
def confirmar_pago(request, tarjeta_id):
    cliente = get_object_or_404(Cliente_natural, pk=1)  # Usando el id 1 como predeterminado
    tarjeta = get_object_or_404(Tarjeta, pk=tarjeta_id)
    with connection.cursor() as cursor:
        cursor.execute(
            """
            select presupuesto_monto_total
            from presupuesto
            where fk_natural = %s and fk_venta is null
            """,
            [cliente.cliente_n_rif]
        )
        row = cursor.fetchone()
        presupuesto_monto_total = row[0] if row else None

   
        cursor.execute(
        """
        select punto_valor
        from punto
        order by punto_id desc
        """,
        )
        row1 = cursor.fetchone()
        punto_valor = row1[0] if row else None

    return render(request, 'sitioweb/confirmar_pago_carrito.html', {'cliente': cliente, 'tarjeta': tarjeta, 'monto_total': presupuesto_monto_total, 'punto_valor': punto_valor})

def pagar_carrito(request, tarjeta_id):
    if request.method == 'POST':
        cantidad_puntos = int(request.POST.get('cantidad_comprar'))
        tarjeta = Tarjeta.objects.get(pk=tarjeta_id)
        cliente = Cliente_natural.objects.get(pk=1)
        print(tarjeta_id)
        print(cliente.cliente_n_rif)
        print(cantidad_puntos)

        with connection.cursor() as cursor:
            cursor.execute("CALL pagar_carrito(%s, %s, %s)", [tarjeta_id, cliente.cliente_n_rif, cantidad_puntos])
            print("hola")
            
        return render(request, 'sitioweb/pago_exitoso.html')  # Renderiza el template del modal    
    
    return render(request, 'sitioweb/productos.html', {'producto': 0})

def afiliacion(request):
    return render(request, 'sitioweb/afiliacion.html')

def seleccionar_tarjeta_afiliacion(request):
    rif_cliente = 1
    # lista_tarjetas = Tarjeta.objects.filter(fk_cliente=rif_cliente)
    cliente = Cliente_natural.objects.get(pk=rif_cliente)

    return render(request, 'sitioweb/seleccionar_tarjeta_afiliacion.html', {'cliente': cliente})

class TarjetaAfiliacionCreateView(generic.CreateView):
    model = Tarjeta
    form_class = TarjetaForm
    template_name = 'sitioweb/registrar_tarjeta_afiliacion.html'
    
    def get_success_url(self):
        # Cambia 'consulta_empleado' por 'consultar_empleado'
        return reverse('sitioweb:seleccionar_tarjeta_afiliacion')
    
    def form_valid(self, form):
        # Obtén el objeto Empleado al que deseas asociar el teléfono
        cliente = get_object_or_404(Cliente_natural, pk=1)
        
        # Guarda el teléfono y asócialo al empleado
        self.object = form.save(commit=False)
        self.object.fk_natural = cliente
        self.object.save()

        return super().form_valid(form)
    
def confirmar_pago(request, tarjeta_id):
    cliente = get_object_or_404(Cliente_natural, pk=1)  # Usando el id 1 como predeterminado
    tarjeta = get_object_or_404(Tarjeta, pk=tarjeta_id)
    with connection.cursor() as cursor:
        cursor.execute(
            """
            select presupuesto_monto_total
            from presupuesto
            where fk_natural = %s and fk_venta is null
            """,
            [cliente.cliente_n_rif]
        )
        row = cursor.fetchone()
        presupuesto_monto_total = row[0] if row else None

   
        cursor.execute(
        """
        select punto_valor
        from punto
        order by punto_id desc
        """,
        )
        row1 = cursor.fetchone()
        punto_valor = row1[0] if row else None

core/sitioweb/templates/sitioweb/afiliacion.html
{% extends 'sitioweb_home.html' %}

{% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <style>
        body {
            background-color: #FFEBCC;
            display: flex;
            flex-direction: column;
            min-height: 100vh; /* Asegura que la página ocupe al menos el alto de la ventana */
        }

        .container {
            flex: 1; /* Hace que la sección de contenido tome el espacio restante */
            padding-top: 20px;
        }

        footer {
            width: 100%;
            bottom: 0;
            position: fixed;
            background-color: #685747;
            color: white;
            padding: 10px;
            font-size: 14px;
            text-align: center;
        }
    </style>

    <div class="container mt-4">
        <h1 class="mb-4">Afiliacion</h1>
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        {% if cliente.tarjetas_natural.all  %}
                            <h2 class="mb-4">Usted ya se encuentra afiliado</h2>
                        {% else %}
                            <p>Usted no se encuentra afiliado</p>
                            <a href="{% url 'sitioweb:seleccionar_tarjeta_afiliacion' %}">afiliarse</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        {% if productos_carrito %}
                            {% with total_carrito=0 %}
                                {% for producto in productos_carrito %}
                                    {% with item_total=producto.0|add:producto.1 %}
                                        {% with total_carrito=total_carrito|add:item_total %}
                                        {% endwith %}
                                    {% endwith %}
                                {% endfor %}
                            {% endwith %}
                            {% if total_carrito %}
                                <h3 class="mb-4">Total a Pagar: {{ total_carrito }}</h3>
                                <button class="btn btn-primary btn-block">Pagar</button>
                                <a href="{% url 'inventario:registrar_inventario' %}">Nuevo</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <strong>ASORONUCAB &copy; 2023 <a href="https://adminlte.io">ASORON</a>.</strong>
        <span>Descubre la excelencia en cada botella.</span>
    </footer>
{% endblock %}

core/sitioweb/templates/sitioweb/carrito.html
{% extends 'sitioweb_home.html' %}

{% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <style>
        body {
            background-color: #FFEBCC;
            display: flex;
            flex-direction: column;
            min-height: 100vh; /* Asegura que la página ocupe al menos el alto de la ventana */
        }

        .container {
            flex: 1; /* Hace que la sección de contenido tome el espacio restante */
            padding-top: 20px;
        }

        footer {
            width: 100%;
            bottom: 0;
            position: fixed;
            background-color: #685747;
            color: white;
            padding: 10px;
            font-size: 14px;
            text-align: center;
        }
    </style>

    <div class="container mt-4">
        <h1 class="mb-4">Carrito de Compras</h1>
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        {% if productos_carrito %}
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Producto</th>
                                        <th scope="col">Cantidad</th>
                                        <th scope="col">Precio Unitario</th>
                                        <th scope="col">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for producto, total in productos_con_total %}
                                        <tr>
                                            <td>{{ producto.2 }}</td>
                                            <td>{{ producto.0 }}</td>
                                            <td>{{ producto.1 }}</td>
                                            <td>{{ total }}</td>
                                            <td>
                                                <form action="{% url 'sitioweb:eliminar_producto' producto.3 %}" method="post">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                                                </form>
                                            </td>
                                            <td>
                                                <form action="{% url 'sitioweb:modificar_cantidad' producto.3 %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="number" name="nueva_cantidad" value="{{ producto.0 }}">
                                                    <button type="submit" class="btn btn-primary btn-sm">Modificar</button>
                                                </form>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <p>No hay productos en el carrito.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        {% if productos_carrito %}
                            {% with total_carrito=0 %}
                                {% for producto in productos_carrito %}
                                    {% with item_total=producto.0|add:producto.1 %}
                                        {% with total_carrito=total_carrito|add:item_total %}
                                        {% endwith %}
                                    {% endwith %}
                                {% endfor %}
                            {% endwith %}
                            {% if total_carrito %}
                                <h3 class="mb-4">Total a Pagar: {{ total_carrito }}</h3>
                                <button onclick="window.location.href = '{% url 'sitioweb:seleccionar_tarjeta' %}'" class="btn btn-primary btn-block">Proceder al pago</button>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <strong>ASORONUCAB &copy; 2023 <a href="https://adminlte.io">ASORON</a>.</strong>
        <span>Descubre la excelencia en cada botella.</span>
    </footer>
{% endblock %}

core/sitioweb/templates/sitioweb/seleccionar_tarjeta.html
{% extends 'sitioweb_home.html' %}

{% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <style>
        body {
            background-color: #FFEBCC;
            display: flex;
            flex-direction: column;
            min-height: 100vh; /* Asegura que la página ocupe al menos el alto de la ventana */
        }

        .container {
            flex: 1; /* Hace que la sección de contenido tome el espacio restante */
            padding-top: 20px;
        }

        footer {
            width: 100%;
            bottom: 0;
            position: fixed;
            background-color: #685747;
            color: white;
            padding: 10px;
            font-size: 14px;
            text-align: center;
        }
    </style>

    <div class="container mt-4">
        <h1 class="mb-4">TARJETAS</h1>
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        {% if cliente.tarjetas_natural.all  %}
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Numero</th>
                                        <th scope="col">Banco</th>
                                        <th scope="col">CVV</th>
                                        <th scope="col">Fecha de Vencimiento</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for tarjeta in cliente.tarjetas_natural.all %}
                                        <tr onclick="window.location='/sitioweb/carrito/confirmar/{{ tarjeta.metodo_pago_id }}/';" style="cursor: pointer;">
                                            <td>{{ tarjeta.tarjeta_numero }}</td>
                                            <td>{{ tarjeta.tarjeta_banco }}</td>
                                            <td>{{ tarjeta.tarjeta_cvv }}</td>
                                            <td>{{ tarjeta.tarjeta_fecha_vencimiento }}</td>
                                            {% comment %} <td>
                                                <form action="{% url 'sitioweb:eliminar_producto' producto.3 %}" method="post">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                                                </form>
                                            </td>
                                            <td>
                                                <form action="{% url 'sitioweb:modificar_cantidad' producto.3 %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="number" name="nueva_cantidad" value="{{ producto.0 }}">
                                                    <button type="submit" class="btn btn-primary btn-sm">Modificar</button>
                                                </form>
                                            </td> {% endcomment %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <a href="{% url 'sitioweb:registrar_tarjeta' %}">Registrar Tarjeta</a>
                        {% else %}
                            <p>No tiene tarjetas registradas</p>
                            <a href="{% url 'sitioweb:registrar_tarjeta' %}">Registrar Tarjeta</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        {% if productos_carrito %}
                            {% with total_carrito=0 %}
                                {% for producto in productos_carrito %}
                                    {% with item_total=producto.0|add:producto.1 %}
                                        {% with total_carrito=total_carrito|add:item_total %}
                                        {% endwith %}
                                    {% endwith %}
                                {% endfor %}
                            {% endwith %}
                            {% if total_carrito %}
                                <h3 class="mb-4">Total a Pagar: {{ total_carrito }}</h3>
                                <button class="btn btn-primary btn-block">Pagar</button>
                                <a href="{% url 'inventario:registrar_inventario' %}">Nuevo</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <strong>ASORONUCAB &copy; 2023 <a href="https://adminlte.io">ASORON</a>.</strong>
        <span>Descubre la excelencia en cada botella.</span>
    </footer>
{% endblock %}