app/urls.py
from core.nomina import views
from django.views.generic import RedirectView
"""
URL configuration for app project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from core.menu.views import login_view

urlpatterns = [
    # Redirección de la URL raíz a '/menu/admin_menu'
    path('', RedirectView.as_view(url='/menu/login/', permanent=True)),
    
    path('admin/', admin.site.urls),
    path('menu/', include("core.menu.urls")),
    path('nomina/', include("core.nomina.urls")),
    path('eventos/', include("core.eventos.urls")),
    path('clientes/', include("core.clientes.urls")),
    path('diario/', include("core.diario.urls")),
    path('dashboard/', include("core.dashboard.urls")),
    path('usuarios/', include("core.usuarios.urls")),
    path('inventario/', include("core.inventario.urls")),
    path('facturacion/', include("core.facturacion.urls")),
    path('sitioweb/', include("core.sitioweb.urls")),
    path('compras/', include("core.compras.urls")),
    path('ventas/', include("core.ventas.urls")),
]

core/diario/urls.py
from django.urls import path

from . import views

app_name = 'diario'

urlpatterns = [
    path('', views.index, name='index'),
    
]

core/inventario/urls.py
from django.urls import path

from . import views

app_name = 'inventario'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.InventarioConsultarView.as_view(), name="consultar_inventario"),
    path("registrar/", views.registrar_inventario, name="registrar_inventario"),
    path("productos/", views.IndexProductoView.as_view(), name="index_producto"),
    path("ofertas/", views.IndexOfertasView.as_view(), name="index_ofertas"),
    path("productos/registrar/", views.BotellaCreateView.as_view(), name="registrar_producto"),
    path("productos/<int:pk>/", views.BotellaConsultarView.as_view(), name="consultar_producto"),
    path("productos/<int:botella_id>/eliminar/", views.eliminar_producto_view, name="eliminar_producto"),
    path("productos/<int:botella_id>/modificar/", views.modificar_producto, name="modificar_producto"),
    path("productos/<int:botella_id>/ficha/", views.ficha_producto, name="ficha_producto"),
    
]

core/inventario/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from core.nomina.models import *
from core.compras.models import *


class MateriaPrima(models.Model):
    materia_prima_id = models.AutoField(primary_key=True)
    materia_prima_nombre = models.CharField(max_length=50)
    materia_prima_tipo = models.CharField(max_length=50)
    materia_prima_descripcion = models.CharField(max_length=150)

    def __str__(self):
        return self.materia_prima_nombre

    class Meta:
        managed = False
        db_table = 'materia_prima'


class Color(models.Model):
    color_id = models.AutoField(primary_key=True)
    color_nombre = models.CharField(max_length=50)
    color_descripcion = models.CharField(max_length=150)

    def __str__(self):
        return self.color_nombre

    class Meta:
        managed = False
        db_table = 'color'

class Tapa(models.Model):
    tapa_id = models.AutoField(primary_key=True)
    tapa_nombre = models.CharField(max_length=50)
    tapa_descripcion = models.CharField(max_length=150)
    fk_materia_prima = models.ForeignKey(MateriaPrima, models.DO_NOTHING, db_column='fk_materia_prima')
    fk_color = models.ForeignKey(Color, models.DO_NOTHING, db_column='fk_color')

    def __str__(self):
        return self.tapa_nombre

    class Meta:
        managed = False
        db_table = 'tapa'


class Ron(models.Model):
    ron_id = models.AutoField(primary_key=True)
    ron_nombre = models.CharField(max_length=50)
    ron_descripcion = models.CharField(max_length=150)
    fk_lugar = models.ForeignKey(Lugar, models.DO_NOTHING, db_column='fk_lugar')
    # fk_barril = models.ForeignKey('barril', models.DO_NOTHING, db_column='fk_barril')
    # fk_tipo_ron = models.ForeignKey('tipo_ron', models.DO_NOTHING, db_column='fk_tipo_ron')
    # fk_mezcla = models.ForeignKey('mezcla', models.DO_NOTHING, db_column='fk_mezcla')

    def __str__(self):
        return self.ron_nombre

    class Meta:
        managed = False
        db_table = 'ron'


class Botella(models.Model):
    botella_id = models.AutoField(primary_key=True)
    botella_nombre = models.CharField(max_length=50)
    botella_precio = models.DecimalField(max_digits=10, decimal_places=2)
    botella_capacidad = models.DecimalField(max_digits=10, decimal_places=2)
    botella_ancho = models.DecimalField(max_digits=10, decimal_places=2)
    botella_alto = models.DecimalField(max_digits=10, decimal_places=2)
    fk_ron = models.ForeignKey(Ron, models.DO_NOTHING, db_column='fk_ron')
    fk_tapa = models.ForeignKey(Tapa, models.DO_NOTHING, db_column='fk_tapa')
    fk_materia_prima = models.ForeignKey(MateriaPrima, models.DO_NOTHING, db_column='fk_materia_prima')
    fk_proveedor = models.ForeignKey(Proveedor, models.DO_NOTHING, db_column='fk_proveedor', blank=True, null=True)

    def __str__(self):
        return self.botella_nombre

    class Meta: 
        managed = False
        db_table = 'botella'


class Inventario(models.Model):
    inventario_id = models.AutoField(primary_key=True)
    inventario_descripcion = models.CharField(max_length=150)
    inventario_cantidad = models.IntegerField()
    fk_botella = models.ForeignKey(Botella, models.DO_NOTHING, db_column='fk_botella')
    fk_departamento = models.ForeignKey(Departamento, models.DO_NOTHING, db_column='fk_departamento')

    def __str__(self):
        return self.inventario_descripcion

    class Meta:
        managed = False
        db_table = 'inventario'

core/inventario/forms.py
from django import forms
from core.inventario.models import *

class BotellaForm(forms.ModelForm):
    class Meta:
        model = Botella
        fields = ['botella_nombre','fk_ron', 'fk_tapa', 'fk_materia_prima', 'fk_proveedor', 'botella_precio', 'botella_capacidad', 'botella_ancho', 'botella_alto']

class InventarioForm(forms.ModelForm):
    class Meta:
        model = Inventario
        fields = ['inventario_cantidad', 'fk_botella','fk_departamento', 'inventario_descripcion']

core/inventario/views.py
from django.shortcuts import render
from core.inventario.models import *
from django.http import HttpResponse, JsonResponse
from core.nomina.models import *
from django.shortcuts import *
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from .forms import *
from django.db import connection, IntegrityError
from django.contrib import messages

class IndexView(generic.ListView):
    template_name = "inventario/index.html"
    context_object_name = "lista_inventario"

    def get_queryset(self):
        """Return the last five published questions."""
        # queryset = Empleado.objects.prefetch_related('telefonos').all()
        queryset = Inventario.objects.all()
        return queryset
    
class IndexProductoView(generic.ListView):
    template_name = "inventario/index_producto.html"
    context_object_name = "lista_botellas"

    def get_queryset(self):
        """Return the last five published questions."""
        # queryset = Empleado.objects.prefetch_related('telefonos').all()
        queryset = Botella.objects.all()
        return queryset
    
class IndexOfertasView(generic.ListView):
    template_name = "inventario/index_ofertas.html"
    context_object_name = "lista_ofertas"
    
    def get_queryset(self):
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM ofertas_view")
            rows = cursor.fetchall()

        return rows
    
class BotellaCreateView(generic.CreateView):
    model = Botella
    form_class = BotellaForm
    template_name = 'inventario/registrar_producto.html'
    
    def get_success_url(self):
        return reverse('inventario:index_producto')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        # Puedes agregar acciones adicionales si es necesario
        return response
    
class BotellaConsultarView(generic.DetailView):
    model = Botella
    template_name = "inventario/consultar_producto.html"
    context_object_name = 'botella'

def eliminar_producto_sql(self, botella_id):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM botella WHERE botella_id = %s", [botella_id])

def eliminar_producto_view(request, botella_id):
    eliminar_producto_sql(request, botella_id)
    return redirect('inventario:index_producto')

def modificar_producto(request, botella_id):
    botella = get_object_or_404(Botella, botella_id=botella_id)

    if request.method == 'POST':
        formulario = BotellaForm(request.POST, instance=botella)
        if formulario.is_valid():
            formulario.save()
        return redirect('inventario:index_producto')
    else:
        formulario = BotellaForm(initial={ 'botella_nombre': botella.botella_nombre, 'fk_ron': botella.fk_ron, 'fk_tapa': botella.fk_tapa, 'fk_materia_prima': botella.fk_materia_prima, 'fk_proveedor': botella.fk_proveedor, 'botella_precio': botella.botella_precio, 'botella_capacidad': botella.botella_capacidad, 'botella_ancho': botella.botella_ancho, 'botella_alto': botella.botella_alto })

    return render(request, 'inventario/modificar_producto.html', {'formulario': formulario})

def registrar_inventario (request):
    if request.method == 'POST':
        formulario = InventarioForm(request.POST)
        if formulario.is_valid():
            inventario_cantidad = formulario.cleaned_data['inventario_cantidad']
            botella = formulario.cleaned_data['fk_botella']
            fk_botella = botella.botella_id
            departamento = formulario.cleaned_data['fk_departamento']
            fk_departamento = departamento.departamento_id
            inventario_descripcion = formulario.cleaned_data['inventario_descripcion']
            print(inventario_cantidad, fk_botella, fk_departamento, inventario_descripcion)

            with connection.cursor() as cursor:
                try:
                    cursor.execute("CALL registrar_inventario(%s, %s, %s, %s)", [inventario_cantidad, fk_botella, fk_departamento, inventario_descripcion])
                    messages.success(request, 'Inventario registrado')
                    return redirect('inventario:index')
                except IntegrityError as e:
                    print(f"Error al registrar el inventario en la base de datos: {e}")
                    messages.error(request, 'Error al registrar el inventario')
                    return JsonResponse({'error': 'Error al registrar el inventario'})
                
    else:
        # Si la solicitud no es un POST, crea un formulario vacío
        formulario = InventarioForm()

    return render(request, 'inventario/registrar_inventario.html', {'formulario': formulario})

class InventarioConsultarView(generic.DetailView):
    model = Inventario
    template_name = "inventario/consultar_inventario.html"
    context_object_name = 'inventario'

def ficha_producto(request, botella_id):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM ficha_producto WHERE botella_id = %s", [botella_id])
        ficha = cursor.fetchone()
        print(ficha)
    return render(request, 'inventario/ficha_producto.html', {'ficha': ficha})

core/inventario/templates/inventario/consultar_producto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Información del Producto</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: Arial, sans-serif;
            background-color: #FFEBCC;
            margin: 0;
            padding: 20px;
        }

        h1 {
            margin-bottom: 20px;
            text-align: center;
        }

        .info-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            width: 600px;
            margin-bottom: 10px;
            padding: 50px;
        }

        .info {
            display: flex;
            flex-direction: column;
            width: 280px;
            margin-bottom: 10px;
        }

        .label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        .value {
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 4px;
            padding: 8px;
        }

        .button-container {
            display: flex;
            flex-direction: row; /* Cambio a dirección horizontal */
            width: 60%; /* O ajusta el ancho según tu preferencia */
            padding: 15px;
            justify-content: space-between; /* Para distribuir los botones */
        }

        .button-agregar {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: #007bff;
        }

        .button-modificar {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: #007bff;
        }

        .button-eliminar {
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: #dc3545;
        }

        .button-lista {
            color: #000000;
            padding: 10px;
            border: none;
            border-radius: 4px;
            text-decoration: none;
            text-align: center;
            margin-bottom: 10px;
            background-color: transparent;
        }


    </style>
</head>
<body>
    <h1>Información del Producto</h1>
    <div class="info-container">
        <div class="info">
            <div class="label">ID:</div>
            <div class="value">{{ botella.botella_id }}</div>
        </div>
        <div class="info">
            <div class="label">Nombre:</div>
            <div class="value">{{ botella.botella_nombre }}</div>
        </div>
        <div class="info">
            <div class="label">Ron:</div>
            <div class="value">{{ botella.fk_ron.ron_nombre }}</div>
        </div>
        <div class="info">
            <div class="label">Capacidad:</div>
            <div class="value">{{ botella.botella_capacidad}}</div>
        </div>
        <div class="info">
            <div class="label">Ancho:</div>
            <div class="value">{{ botella.botella_ancho }}</div>
        </div>
        <div class="info">
            <div class="label">Alto:</div>
            <div class="value">{{ botella.botella_alto}}</div>
        </div>
    </div>

    <div class="button-container">
        <a href="{% url 'inventario:ficha_producto' botella.botella_id %}" class="button-modificar">Ficha</a>
        <a href="{% url 'inventario:modificar_producto' botella.botella_id %}" class="button-modificar">Modificar Producto</a>
        <a href="#" onclick="mostrarModal()" class="button-eliminar">Eliminar Producto</a>
        <a href="{% url 'inventario:index_producto' %}" class="button-lista">Volver a la lista de Productos</a>
    </div>
    </div>
    <!-- Modal -->
    <div id="myModal" class="modal" style="display: none;">
        <div class="modal-content">
            <span class="close" onclick="cerrarModal()">&times;</span>
            {% include 'inventario/eliminar_producto.html' %}
        </div>
    </div>

    <script>
        function mostrarModal() {
            document.getElementById('myModal').style.display = 'block';
        }

        function cerrarModal() {
            document.getElementById('myModal').style.display = 'none';
        }
    </script>
</body>
</html>

core/inventario/templates/inventario/eliminar_producto.html
<!DOCTYPE html>
<html lang="en">
<style>
    .modal {
    display: none;
    position: fixed;
    z-index: 1;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgba(0,0,0,0.4);
    }

    /* Contenido del modal */
    .modal-content {
    background-color: #fefefe;
    margin: 15% auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
    }

    /* Botón para cerrar el modal */
    .close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
    }

    .close:hover,
    .close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
    }

    #eliminarForm {
        margin-top: 20px;
    }

    #eliminarForm input[type="submit"] {
        padding: 15px 25px;
        background-color: #dc3545;
        color: white;
        border: none;
        border-radius: 4px;
        text-decoration: none;
        text-align: center;
        font-size: 16px;
        cursor: pointer;
    }

    #eliminarForm input[type="submit"]:hover {
        background-color: #c82333;
    }
</style>
<body>
    <h2>¿Estás seguro de que deseas eliminar el producto "{{ botella.botella_id }} {{ botella.fk_ron.ron_nombre }}"?</h2>

    <form id="eliminarForm" method="post" action="{% url 'inventario:eliminar_producto' botella.botella_id %}">
        {% csrf_token %}
        <input type="submit" value="Eliminar">
    </form>

    <script>
        // Función para mostrar el modal
        function mostrarModal() {
            document.getElementById('myModal').style.display = 'block';
        }

        // Función para cerrar el modal
        function cerrarModal() {
            document.getElementById('myModal').style.display = 'none';
        }

        // Evento al enviar el formulario en el modal
        document.getElementById('modalEliminarForm').addEventListener('submit', function() {
            document.getElementById('modalEliminarForm').action = "{% url 'inventario:eliminar_producto' botella.botella_id %}";
        });
    </script>
</body>
</html>

core/inventario/templates/inventario/index.html
{% extends 'home.html'%}

{% block body%}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">

    {% include 'header.html'%}

    <div class="content-wrapper">
        
        <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">
                        <i class="bi bi-stack mr-2 " style="color: #685747;"></i> Inventario
                    </h1>
                </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'inventario:registrar_inventario' %}">Nuevo</a></li>
                <li class="breadcrumb-item"><a href="{% url 'inventario:index_producto' %}">Productos</a></li>
                <li class="breadcrumb-item"><a href="{% url 'inventario:index_ofertas' %}">Ofertas</a></li>
                </ol>
            </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
        </div>
        <div class = "content">
            <div class = "container"> 
                {% block content%}
                <style>
                    .espaciado {
                        margin-bottom: 20px; /* Espaciado en la parte inferior */
                        padding-left: 10px;  /* Espaciado en el lado izquierdo */
                        margin-left: auto;
                        margin-right: auto;
                    }
                
                    body {
                      font-family: Arial, sans-serif;
                  }
                
                  h2 {
                      margin-bottom: 20px;
                  }
                
                  table {
                      border-collapse: collapse;
                      width: 80%;
                      margin-left: auto;
                      margin-right: auto; 
                  }
                
                  th, td {
                      padding: 12px;
                      text-align: left;
                      border-bottom: 1px solid #ddd;
                  }
                
                  tbody tr:hover {
                      background-color: #DDDDDD;
                  }
                
                  /* Estilos adicionales para mejorar la apariencia */
                  th {
                      background-color: #f2f2f2;
                  }
                  </style>
                    <table border="1", style = espaciado>
                        <thead>
                            <tr>
                                <th>Producto</th>
                                <th>Cantidad</th>
                                <th>Precio Unitario</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for inventario in lista_inventario %}
                                <tr onclick="window.location='/inventario/{{ inventario.inventario_id }}';" style="cursor: pointer;">
                                    <td>{{ inventario.fk_botella.fk_ron.ron_nombre }} {{ inventario.fk_botella.botella_nombre }}</td>
                                    <td>{{ inventario.inventario_cantidad }}</td>                                                         
                                    <td>{{ inventario.fk_botella.botella_precio }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'footer.html'%}
    </div>
    </body>
{% endblock %}

core/inventario/templates/inventario/index_ofertas.html
{% extends 'home.html'%}

{% block body%}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">

    {% include 'header.html'%}

    <div class="content-wrapper">
        
        <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">
                        <i class="bi bi-stack mr-2 " style="color: #685747;"></i> Ofertas
                    </h1>
                </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'diario:index' %}">Ver Diario</a></li>
                <li class="breadcrumb-item"><a href="{% url 'inventario:index_producto' %}">Productos</a></li>
                <li class="breadcrumb-item"><a href="{% url 'inventario:index' %}">Inventario</a></li>
                </ol>
            </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
        </div>
        <div class = "content">
            <div class = "container"> 
                {% block content%}
                <style>
                    .espaciado {
                        margin-bottom: 20px; /* Espaciado en la parte inferior */
                        padding-left: 10px;  /* Espaciado en el lado izquierdo */
                        margin-left: auto;
                        margin-right: auto;
                    }
                
                    body {
                      font-family: Arial, sans-serif;
                  }
                
                  h2 {
                      margin-bottom: 20px;
                  }
                
                  table {
                      border-collapse: collapse;
                      width: 80%;
                      margin-left: auto;
                      margin-right: auto; 
                  }
                
                  th, td {
                      padding: 12px;
                      text-align: left;
                      border-bottom: 1px solid #ddd;
                  }
                
                  tbody tr:hover {
                      background-color: #DDDDDD;
                  }
                
                  /* Estilos adicionales para mejorar la apariencia */
                  th {
                      background-color: #f2f2f2;
                  }
                  </style>
                    <table border="1", style = espaciado>
                        <thead>
                            <tr>
                                <th>ID Producto</th>
                                <th>Nombre</th>
                                <th>Precio Unitario</th>
                                <th>Cantidad disponible</th>
                                <th>Descuento</th>
                                <th>Fecha inicio</th>
                                <th>Fecha fin</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for oferta in lista_ofertas %}
                                <tr onclick="window.location='';" style="cursor: pointer;">
                                    <td>{{ oferta.0 }}</td>     
                                    <td>{{ oferta.1 }}</td>   
                                    <td>{{ oferta.2 }}</td>   
                                    <td>{{ oferta.3 }}</td>                                                       
                                    <td>{{ oferta.4 }}</td>
                                    <td>{{ oferta.5 }}</td>
                                    <td>{{ oferta.6 }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'footer.html'%}
    </div>
    </body>
{% endblock %}

core/inventario/templates/inventario/index_producto.html
{% extends 'home.html'%}

{% block body%}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">

    {% include 'header.html'%}

    <div class="content-wrapper">
        
        <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">
                        <i class="bi bi-view-stacked mr-2" style="color: #685747;"></i> Productos
                    </h1>
                </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'inventario:registrar_producto' %}">Nuevo</a></li>
                <li class="breadcrumb-item"><a href="{% url 'inventario:index' %}">Inventario</a></li>
                <li class="breadcrumb-item"><a href="{% url 'inventario:index_ofertas' %}">Ofertas</a></li>
                </ol>
            </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
        </div>
        <div class = "content">
            <div class = "container"> 
                {% block content%}
                <style>
                    .espaciado {
                        margin-bottom: 20px; /* Espaciado en la parte inferior */
                        padding-left: 10px;  /* Espaciado en el lado izquierdo */
                        margin-left: auto;
                        margin-right: auto;
                    }
                
                    body {
                      font-family: Arial, sans-serif;
                  }
                
                  h2 {
                      margin-bottom: 20px;
                  }
                
                  table {
                      border-collapse: collapse;
                      width: 80%;
                      margin-left: auto;
                      margin-right: auto; 
                  }
                
                  th, td {
                      padding: 12px;
                      text-align: left;
                      border-bottom: 1px solid #ddd;
                  }
                
                  tbody tr:hover {
                      background-color: #DDDDDD;
                  }
                
                  /* Estilos adicionales para mejorar la apariencia */
                  th {
                      background-color: #f2f2f2;
                  }
                  </style>
                    <table border="1", style = espaciado>
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Ron</th>
                                <th>Precio</th>
                                <th>Capacidad (L)</th>
                                <th>Ancho</th>
                                <th>Alto</th>                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for botella in lista_botellas %}
                                <tr onclick="window.location='/inventario/productos/{{ botella.botella_id }}';" style="cursor: pointer;">
                                    <td>{{ botella.botella_nombre }}</td>
                                    <td>{{ botella.fk_ron.ron_nombre }}</td>   
                                    <td>{{ botella.botella_precio }}</td>                   
                                    <td>{{ botella.botella_capacidad }}</td>                            
                                    <td>{{ botella.botella_ancho}}</td>
                                    <td>{{ botella.botella_alto }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'footer.html'%}
    </div>
    </body>
{% endblock %}